language: c

env:
  matrix:
    - "LUA=lua5.1 LUACTOR_REACTOR=luaevent"
    - "LUA=lua5.1 LUACTOR_REACTOR=uloop"

install:
  - "source tests/setup.sh"

script:
  - "source tests/run_tests.sh"

after_success:
  - "$LUA tests/report_coverage.lua"
  - 'curl -v -H "Content-Type: multipart/related" --form "json_file=@tests/luacov.report.json;type=application/json" https://coveralls.io/api/v1/jobs'

